require:
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true
AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'mysql-data/**/*'
    - 'bin/**/*'
    - 'front/**/*'
  TargetRubyVersion: 2.7.2
Documentation:
  Enabled: false
Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/20210707041603_devise_create_users.rb'
