require:
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true
AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'mysql-data/**/*'
    - 'bin/**/*'
    - 'front/**/*'
  TargetRubyVersion: 2.7.2
Documentation:
  Enabled: false
