version: "3"
services:
  mysql:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: tracker_web
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: tracker_web_production
      TZ: Asia/Tokyo
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
  influx_db:
    image: influxdb:2.0
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: tracker
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: tracker
      DOCKER_INFLUXDB_INIT_BUCKET: tracker_db
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: token
    volumes:
      - ./influx_db/data:/var/lib/influxdb2
      - ./influx_db/scripts:/docker-entrypoint-initdb.d
    ports:
      - "8086:8086"
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - 4444:4444
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
