apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: tracker
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: rk221/tracker_rails
          command:
            - /bin/bash
          args:
            - -c
            - bundle exec rails db:migrate
          env:
            - name: RAILS_ENV
              value: production
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: RAILS_MASTER_KEY
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: REDIS_URL
            - name: TRACKER_DATABASE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: TRACKER_DATABASE_DATABASE
            - name: TRACKER_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: TRACKER_DATABASE_USERNAME
            - name: TRACKER_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: TRACKER_DATABASE_PASSWORD
            - name: TRACKER_DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: TRACKER_DATABASE_HOST
            - name: TRACKER_DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: TRACKER_DATABASE_PORT
            - name: TRACKER_ALLOW_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: TRACKER_ALLOW_ORIGINS
            - name: TRACKER_FRONT_URL
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: TRACKER_FRONT_URL
            - name: TRACKER_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: TRACKER_SMTP_PASSWORD
            - name: TRACKER_SMTP_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: TRACKER_SMTP_DOMAIN
            - name: TRACKER_SMTP_FROM
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: TRACKER_SMTP_FROM
            - name: INFLUX_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: INFLUX_DB_HOST
            - name: INFLUX_DB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: INFLUX_DB_TOKEN
            - name: INFLUX_DB_ORG
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: INFLUX_DB_ORG
            - name: INFLUX_DB_BUCKET
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: INFLUX_DB_BUCKET
            - name: RAILS_LOG_TO_STDOUT
              value: enabled
